beautybook/Controllers/InvoicesController.cs
using BeautyBook.Infrastructure;
using BeautyBook.Pages;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace BeautyBook.Controllers
{
    public class InvoicesController : BaseController
    {
        public ActionResult SiplifedInvoice()
        {
            return View();
        }

        public ActionResult ReturnInvoice(string RI = "MA==")
        {
            ViewBag.ReturnInvoiceId = RI;
            return View();
        }

        public ActionResult TaxInvoice()
        {
            return View();
        }

        public ActionResult TaxInvoiceDetails()
        {
            return View();
        }
    }
}

beautybook/Controllers/PosController.cs
using BeautyBook.Common;
using BeautyBook.Infrastructure;
using BeautyBook.Pages;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace BeautyBook.Controllers
{
    public class PosController : BaseController
    {
        public ActionResult Index(string ri = "MA==")
        {


            if (Request.Cookies["SalonName"] != null)
            {
                ViewBag.SalonName = Request.Cookies["SalonName"].Value;
            }

            if (Request.Cookies["PosAuthEmail"] != null)
            {
                ViewBag.PosAuthEmail = Request.Cookies["PosAuthEmail"].Value;
            }


            int DecodeId = Convert.ToInt32(ConvertTo.Base64Decode(ri));
            ViewBag.ri = DecodeId;
            
            return View();
        }

        public ActionResult Sessions()
        {
            return View();
        }
        
        public ActionResult ReturnInvoice()
        {
            return View();
        }

        public ActionResult CreateSessions()
        {
            return View();
        }

		public ActionResult ManageSession(string ri = "MA==")
		{

			ViewBag.SessionId = ri;
			return View();
		}

		public ActionResult Orders(string ri = "MA==")
        {
			int DecodeSessionId = Convert.ToInt32(ConvertTo.Base64Decode(ri));
			ViewBag.SessionId = DecodeSessionId;
			return View();
        }

        public ActionResult PosAuthentication()
        {
            return View();
        }   
        
        public ActionResult SiplifedInvoice()
        {
            return View();
        }

        public ActionResult PosInvoice(string ri = "MA==")
        {

            ViewBag.ri = ri;

            return View();
        }
    }
}

beautybook/Views/Pos/CreateSessions.cshtml
@{
    ViewBag.Title = "Create Session";
}
<style>
    .coin-cash::-webkit-inner-spin-button,
    .coin-cash::-webkit-outer-spin-button {
        opacity: 1 !important;
    }

    .coin-cash {
        border: none;
        border-bottom: 3px solid #7e7e7e;
        border-radius: 0;
    }
</style>
<main class="app-content">
    <div class="app-content-wrapper">
        <div class="app-content-title">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column flex-sm-row align-items-sm-center">
                            <h6 class="mb-0 pb-3 pb-sm-0 order-2 order-sm-1 mr-auto">@beautybook.Resources.Languages.Create_Session</h6>
                            <nav aria-label="breadcrumb" class="order-1 order-sm-2 ml-sm-3">
                                <ol class="breadcrumb mb-0 pl-0">
                                    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">@(beautybook.Resources.Languages.Dashboard)</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">@beautybook.Resources.Languages.Create_Session</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="app-content-inner">
            <div class="container">
                <div id="loader" style="display: none;" class="text-center mb-2 mt-2">
                    <img src='~/Content/assets/images/ajax-loader.gif' width='32px' height='32px'>
                </div>
                <div class="row" id="posSessionCard">
                    @*<div class="badge badge-danger">To Close</div>*@
                </div>
            </div>
        </div>
    </div>
</main>
<br />
<br />

<div class="modal fade p-0" id="cashControl" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="cashControl" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-zoom modal-fullscreen-md-down">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cashControl">@beautybook.Resources.Languages.Opening_Cash_Control</h5>
                <button type="button" onclick="location.reload();" class="modal-close close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form class="row" id="salonsForm" name="salonsForm" novalidate="novalidate">
                <div class="modal-body">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12 mb-3">
                                <div class="row m-0" id="CoinsAmount">
                                    @*<div class="col-lg-3 p-1 text-center d-flex" style="align-items: center;">
                                            <label class="mb-0" style="font-weight:500;width: 100%;">SAR 10</label>
                                            <div class="d-flex align-items-center">
                                                <input type="number" id="amount_0" value="0" class="form-control coin-cash">
                                                <div class="count-arrow">
                                                    <i class="filter-arrow bb-chevron-up" onclick="PlusMinusAmount(0,true,10)"></i>
                                                    <i class="filter-arrow bb-chevron-down" onclick="PlusMinusAmount(0,false,10)"></i>
                                                </div>
                                            </div>
                                        </div>*@
                                    @*<div class="col-lg-3 p-1 text-center d-flex" style="align-items: center;">
                                            <label class="mb-0" style="font-weight:500;width: 100%;">SAR 20</label>
                                            <div class="d-flex align-items-center">
                                                <input type="number" id="amount_1" value="0" class="form-control coin-cash">
                                                <div class="count-arrow">
                                                    <i class="filter-arrow bb-chevron-up" onclick="PlusMinusAmount(1,true,20)"></i>
                                                    <i class="filter-arrow bb-chevron-down" onclick="PlusMinusAmount(1,false,20)"></i>
                                                </div>
                                            </div>
                                        </div>*@
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <h5 style="text-align:end;">SAR : <span id="cashtotal_amount">0</span></h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="modal-footer w-100">
                        <button type="button" onclick="CreatePosSession();" class="btn btn-primary" id="sessionBtn">
                            @beautybook.Resources.Languages.Open_Session
                        </button>
                        <button type="button" class="btn btn-primary" id="sessionLoadingBtn" disabled style="display:none;">
                            @beautybook.Resources.Languages.Open_Session
                            <i class="fa fa-circle-o-notch ml-1 fa-spin" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Core Scripts -->
<script src="~/Content/assets/js/jquery/jquery-3.6.0.min.js"></script>
<script src="~/Content/assets/js/popper/popper.min.js"></script>
<script src="~/Content/BeautyBookAPI/PosApi/CoinsAmount.js"></script>
<script src="~/Content/BeautyBookAPI/PosApi/PosSession.js"></script>

<script>
    //getCookie
    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    //setCookie
    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    //NewSession
    function NewSession() {
        $("#cashControl").modal("show");
    }


    $(document).ready(function () {
        PosCard();

        CoinsAmount();
    })

    //plushAmount
    var amountSum = 0;
    function PlusMinusAmount(index, isPlush, amount) {
        var countGet = parseInt($("#amount_" + index).val());

        if (isPlush == true) {
            countGet = countGet + 1;
            amountSum = amountSum + amount;

        }
        else if (isPlush == false && countGet > 0) {
            countGet = countGet - 1;
            amountSum = amountSum - amount;
        }

        $("#amount_" + index).val(countGet);
        $("#cashtotal_amount").text(amountSum.toFixed(2));
    }
</script>

beautybook/Views/Pos/Orders.cshtml
@{
    ViewBag.Title = "Pos Orders";
}
<style>
    .coin-cash::-webkit-inner-spin-button,
    .coin-cash::-webkit-outer-spin-button {
        opacity: 1 !important;
    }

    .coin-cash {
        border: none;
        border-bottom: 3px solid #7e7e7e;
        border-radius: 0;
    }
</style>
<main class="app-content">
    <div class="app-content-wrapper">
        <div class="app-content-title">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column flex-sm-row align-items-sm-center">
                            <h6 class="mb-0 pb-3 pb-sm-0 order-2 order-sm-1 mr-auto">Pos Orders</h6>
                            <nav aria-label="breadcrumb" class="order-1 order-sm-2 ml-sm-3">
                                <ol class="breadcrumb mb-0 pl-0">
                                    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">@(beautybook.Resources.Languages.Dashboard)</a></li>
                                    <li class="breadcrumb-item"><a href="@Url.Action("ManageSession","Pos")">Manage Session</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Pos Orders</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="app-content-inner">
            <div class="container">
                <div class="tab-content">
                    <div class="tab-pane fade active show" id="grid-view" role="tabpanel">
                        <div class="row">
                            <div class="col-12">
                                <div class="table-responsive table-hover fs-14">
                                    <div class="posOrderDatalistdiv">
                                        <table id="posOrderDatalist" class="table table-card" style="width:100%; display:inherit;">
                                        </table>
                                        <div id="loader" style="display: none;" class="text-center mb-2 mt-2">
                                            <img src='~/Content/assets/images/ajax-loader.gif' width='32px' height='32px'>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<br />
<br />

<!-- Pos Order Modal -->
<div class="modal fade" id="posOrderDetailsModal" tabindex="-1" aria-labelledby="posOrderDetailsLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-fullscreen-md-down modal-dialog-right modal-dialog-scrollable">
        <form class="modal-content">
            <div class="modal-header bg-primary flex-column align-items-start pb-0">
                <div class="d-flex justify-content-between w-100 mb-2">
                    <h5 class="modal-title text-white" id="posOrderDetailsLabel">Pos Order Services</h5>
                    <button type="button" class="modal-close close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <div class="modal-body">
                <div class="row fs-14 m-0" id="posOrderDetails">
                    
                </div>
                <div id="posOrderDetailsloader" style="display: none;" class="text-center mb-2 mt-2">
                    <img src='~/Content/assets/images/ajax-loader.gif' width='32px' height='32px'>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Core Scripts -->
<script>
    var SessionId = @ViewBag.SessionId;
</script>
<script src="~/Content/assets/js/jquery/jquery-3.6.0.min.js"></script>
<script src="~/Content/assets/js/popper/popper.min.js"></script>
<script src="~/Content/BeautyBookAPI/PosApi/ManageOrders/ManageOrders.js"></script>

<script>
    
    //getCookie
    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    //setCookie
    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    $(document).ready(function () {
        ArbicLanguage();


        PosOrderList.init();

    })
</script>

beautybook/Views/Pos/PosAuthentication.cshtml
@{
    ViewBag.Title = "Pos Authentication";
}
<style>
    .coin-cash::-webkit-inner-spin-button,
    .coin-cash::-webkit-outer-spin-button {
        opacity: 1 !important;
    }

    .coin-cash {
        border: none;
        border-bottom: 3px solid #7e7e7e;
        border-radius: 0;
    }
</style>
<main class="app-content">
    <div class="app-content-wrapper">
        <div class="app-content-title">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column flex-sm-row align-items-sm-center">
                            <h6 class="mb-0 pb-3 pb-sm-0 order-2 order-sm-1 mr-auto">Pos Authentication</h6>
                            <nav aria-label="breadcrumb" class="order-1 order-sm-2 ml-sm-3">
                                <ol class="breadcrumb mb-0 pl-0">
                                    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">@(beautybook.Resources.Languages.Dashboard)</a></li>
                                    <li class="breadcrumb-item"><a href="@Url.Action("Sessions","Pos")">Sessions</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Pos Authentication</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="app-content-inner">
            <div class="container">
                <div class="row justify-content-center align-items-center" style="height:70vh;">
                    <div class="col-lg-6">
                        <div class="card p-3">
                            <div class="mb-5 w-100 text-left">
                                <h4>Pos Authentication</h4>
                                <p class="mb-0">You can use the salon owner's email address to login</p>
                            </div>
                            <div class="row m-0 align-items-center">
                                <div class="col-lg-12 p-0">
                                    <form id="PosAuthentication" name="PosAuthentication">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="text" class="form-control form-control-lg" tabindex="1" name="PosEmail" id="PosEmail" placeholder="email@address.com">
                                        </div>

                                        <div class="d-flex justify-content-center">
                                            <button type="submit" tabindex="3" role="button" id="userSignInbtn" class="btn btn-lg btn-block btn-primary" value="Submit">Login and Continue</button>
                                        </div>
                                    </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<br />
<br />

<div class="modal fade p-0" id="cashControl" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="cashControl" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-zoom modal-fullscreen-md-down">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cashControl">Opening Cash Control</h5>
                <button type="button" onclick="location.reload();" class="modal-close close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form class="row" id="salonsForm" name="salonsForm" novalidate="novalidate">
                <div class="modal-body">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12 mb-3">
                                <div class="row m-0" id="CoinsAmount">
                                  
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <h5 style="text-align:end;">SAR : <span id="cashtotal_amount">0</span></h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="modal-footer w-100">
                        <button type="button" onclick="CreatePosSession();" class="btn btn-primary" id="sessionBtn">
                            Open Session
                        </button>
                        <button type="button" class="btn btn-primary" id="sessionLoadingBtn" disabled style="display:none;">
                            Open Session
                            <i class="fa fa-circle-o-notch ml-1 fa-spin" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



<!-- Core Scripts -->
<script src="~/Content/assets/js/jquery/jquery-3.6.0.min.js"></script>
<script src="~/Content/assets/js/popper/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="~/Content/BeautyBookAPI/PosApi/CoinsAmount.js"></script>
<script src="~/Content/BeautyBookAPI/PosApi/PosSession.js"></script>

<script>

    $(function () {
        $("form[name='PosAuthentication']").validate({
            rules: {
                PosEmail: {
                    required: true,
                    email: true
                }
            },
            messages: {
                PosEmail: {
                    required:  "@(beautybook.Resources.Languages.Email_is_required)",
                },
            },
            submitHandler: function () {
                PosAuthentication();
            }
        });
    });

    //getCookie
    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    //setCookie
    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    //NewSession
    function NewSession() {
        $("#cashControl").modal("show");
    }


    $(document).ready(function () {
        CoinsAmount();
    })

    //plushAmount
    var amountSum = 0;
    function PlusMinusAmount(index, isPlush, amount) {
        var countGet = parseInt($("#amount_" + index).val());

        debugger;
        if (isPlush == true) {
            countGet = countGet + 1;
            amountSum = amountSum + amount;

        }
        else if (isPlush == false && countGet > 0) {
            countGet = countGet - 1;
            amountSum = amountSum - amount;
        }

        $("#amount_" + index).val(countGet);
        $("#cashtotal_amount").text(amountSum.toFixed(2));
    }
</script>

beautybook/Views/Pos/SiplifedInvoice.cshtml
@using BeautyBook.Common;
@{
    ViewBag.Title = "POS Siplifed Invoice";
}
<main class="app-content">

    <div class="app-content-wrapper">
        <div class="app-content-title">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column flex-sm-row align-items-sm-center">
                            <h6 class="mb-0 pb-3 pb-sm-0 order-2 order-sm-1 mr-auto">@beautybook.Resources.Languages.Manage_Invoice</h6>
                            <nav aria-label="breadcrumb" class="order-1 order-sm-2 ml-sm-3">
                                <ol class="breadcrumb mb-0 pl-0">
                                    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">@(beautybook.Resources.Languages.Dashboard)</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">@(beautybook.Resources.Languages.Manage_Invoice) </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="app-content-header text-left-to-right">
            <form class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-5 row-cols-xxl-5 align-items-center align-items-xl-end">
                    <div class="col-lg-2">
                        <label for="employeeName" class="custom-label">@(beautybook.Resources.Languages.Date)</label>
                        <div class="col-sm-12 p-0">
                            <div class="input-group">
                                <input type="text" class="datepicker w-100 singledatepicker form-control" placeholder="" name="PosInvoiceDate" tabindex="3" id="PosInvoiceDate">
                                <div class="input-group-append input-box-label">
                                    <span class="input-group-text text-muted">
                                        <i class="bb-calendar fs-21"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group mb-xl-0">
                            <label for="employeeStatus" class="custom-label">@(beautybook.Resources.Languages.Invoice_Number)</label>
                            <div class="d-flex align-items-center" style="position: relative;">
                                <p class="mb-0" style="position: absolute; left: 10px;">#</p>
                                <input type="text" id="PosInvoiceNumber" name="PosInvoiceNumber" class="form-control" value="" style="padding-left: 25px;" />
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group mb-xl-0">
                            <label for="employeeStatus" class="custom-label">@(beautybook.Resources.Languages.Customer_Name)</label>
                            <select class="selectpicker form-control" data-live-search="true" id="PosCustomerName" name="PosCustomerName" title="@(beautybook.Resources.Languages.Select_a_option)">
                            </select>
                        </div>
                    </div>

                    <div class="col">
                        <button type="button" class="btn btn-primary btn-wide" tabindex="4" id="Searchbtn" onclick="SiplifedInvoiceSearch();">@(beautybook.Resources.Languages.Search)</button>
                        <button type="button" class="btn btn-primary btn-wide" id="Searchbtnloading" disabled style="display:none;">
                            @(beautybook.Resources.Languages.Search)  <i class="fa fa-circle-o-notch ml-1 fa-spin" aria-hidden="true"></i>
                        </button>
                        <button type="button" class="btn btn-link btn-sm fs-13 text-muted" tabindex="5" onclick="ResetSiplifedInvoice();" id="ResetDatabtn">@(beautybook.Resources.Languages.Reset)</button>
                        <button type="button" class="btn btn-link btn-sm fs-13 text-muted" id="Resetbtnloading" disabled style="display:none;">
                            @(beautybook.Resources.Languages.Reset) <i class="fa fa-circle-o-notch ml-1 fa-spin" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>


        <div class="app-content-inner">
            <div class="container">
                @if
                (
                   @ProjectSession.EmployeePermission.Item.Where(x => x.ModuleKey == "AppointmentInvoice").FirstOrDefault().Value == true &&
                   @ProjectSession.EmployeePermission.Item.Where(x => x.ModuleKey == "POSInvoice").FirstOrDefault().Value == true
                )
                {
                    <div class="text-center">
                        <ul class="nav nav-pills bg-white p-1 mr-2 rounded d-inline-flex" role="tablist">
                            <li class="nav-item" role="presentation">
                                <a class="nav-link" href="@Url.Action("SiplifedInvoice","Invoices")" style="cursor:pointer;">Appointment</a>
                            </li>
                            <li class="nav-item" role="presentation">
                                <a class="nav-link active" href="@Url.Action("SiplifedInvoice","Pos")" style="cursor:pointer;">POS</a>
                            </li>
                        </ul>
                    </div>
                }
                
                <div class="tab-content">
                    <div class="tab-pane fade  active show" id="grid-view" role="tabpanel">
                        <div class="row">
                            <div class="col-12">
                                <div class="table-responsive table-hover fs-14">
                                    <div id="SiplifedInvoiceDiv">
                                        <table id="SiplifedInvoice" class="table table-card" style="width:100%; display:inherit;">
                                        </table>
                                        <div id="ManageListingloader" style="display:none;" class="text-center mb-2 mt-2">
                                            <img src='~/Content/assets/images/ajax-loader.gif' width='32px' height='32px'>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="card-view" role="tabpanel">
                        <div class="row" id="defualtServiceSelect">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


<!-- Core Scripts -->
<script src="~/Content/assets/js/jquery/jquery-3.6.0.min.js"></script>
<script src="~/Content/assets/js/popper/popper.min.js"></script>

<!-- Custom JS -->
<script src="~/Content/assets/js/main.js"></script>


@*API JS FILE*@
<script src="~/Content/BeautyBookAPI/APIEndPoint.js"></script>
<script src="~/Content/BeautyBookAPI/PosApi/ManageSiplifedInvoice/ManageSiplifedInvoice.js"></script>
<script src="~/Content/BeautyBookAPI/PosApi/PosReturnInvoice/ReturnInvoice.js"></script>


<script>
    $(document).ready(function () {
        ArbicLanguage();
        //SiplifedInvoice API function call
        SiplifedInvoiceList.init();

        //InvoiceCustomers list
        InvoiceCustomers();
    });
</script>